name: Notificações do Telegram

on:
  schedule:
    # Expressão cron: 10, 15 e 22 horas (UTC) – lembre-se que agora o código interpretará os horários como de Brasília
    - cron: '0 10,15,22 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      TZ: America/Sao_Paulo

    steps:
      - name: Fazer requisição para o endpoint do Vercel
        run: |
          echo "Disparando endpoint de notificações..."
          curl -X POST https://my-calendar-telegram.vercel.app/api/telegram
